### ISSUE TITLE
睡眠唤醒问题

### ISSUE THREAD

**Issue by vectorstone** [Mr-Zhang-1/Dell5557-I5-6200U-bigsur-Monterey-OC#1]
合上盖子，再打开盖子，有一定的几率会出现键盘失灵（按任何按键都没有反应，触摸板正常），登录界面自动输入的情况，导致无法进入系统
系统版本：Big Sur 11.5.2
OC版本：0.7.3

**Comment by nidemimihihi** [comment]
我得电脑没有这个问题，所以我不清楚什么原因

**Comment by vectorstone** [comment]
好的，谢谢，我再去google上看看有没有类似情况
