### ISSUE TITLE
大佬，我和你相同机型，已经安装上了，但是换了你这个卡代码了

### ISSUE THREAD

**Issue by opensilence** [Mr-Zhang-1/Dell5557-I5-6200U-bigsur-Monterey-OC#3]
卡了attempting system restart    mach reboot

**Comment by opensilence** [comment]
![fa59e021b9818d0f97fc297e1c25068](https://user-images.githubusercontent.com/79587530/158041810-6638c431-9492-4416-b949-46a05968acb7.jpg)

**Comment by nidemimihihi** [comment]
你把显卡参数改为123456787然后再装看看

**Comment by nidemimihihi** [comment]
装完改回去

**Comment by opensilence** [comment]
已经装完了，我用的万能efi装的啥都没有，然后cfg也解锁了，但是就是进不去

**Comment by opensilence** [comment]
加了12345678也进不去，咋办大佬

**Comment by nidemimihihi** [comment]
你加我q，1444565439

**Comment by ericlesvinicius** [comment]
hello i have the same problem, how do i solve it, can you help me?

**Comment by ericlesvinicius** [comment]
Which parameter exactly do I have to change in config.plist?

**Comment by nidemimihihi** [comment]
> Which parameter exactly do I have to change in config.plist?
> 

I don't know what your configuration is. Generally ,the problem is that the config is not configured properly. Check carefully and you'd better reconfigure it. Here are some solutions to some problems. The link is here : http://imacos.top/2021/01/19/0154/

**Comment by ericlesvinicius** [comment]
My setup is exactly what you are using. DELL 5557 i5-6200u .

**Comment by ericlesvinicius** [comment]
My setup is exactly what you are using. DELL 5557 i5-6200u .

**Comment by nidemimihihi** [comment]
> My setup is exactly what you are using. DELL 5557 i5-6200u .

Are you using the latest version 0.7.9?

**Comment by ericlesvinicius** [comment]
yes, but I've tried to use other versions but also the error. I'll send you a picture of the error.

**Comment by ericlesvinicius** [comment]
![erro](https://user-images.githubusercontent.com/102456133/160310138-a08d8826-5c99-4c2b-80cb-3a2ca7acc238.jpeg)

this is giving in version 0.7.9.

**Comment by ericlesvinicius** [comment]
![erro2](https://user-images.githubusercontent.com/102456133/160311986-1f27eac9-5e9b-460e-a805-79d29efafcdd.jpeg)

This error is giving in version 0.7.8.

**Comment by nidemimihihi** [comment]
> yes, but I've tried to use other versions but also the error. I'll send you a picture of the error.

You leave an email, I'll look at the EFI problem after work, handle it and send it to your email

**Comment by ericlesvinicius** [comment]
OK. my email is ( barbosa.ericles@gmail.com ). Hope you help me friend. I'm using macOS BigSur version 11.6.5.

**Comment by nidemimihihi** [comment]
> OK. my email is ( barbosa.ericles@gmail.com ). Hope you help me friend. I'm using macOS BigSur version 11.6.5.

I've sent it to your email address, and you just need to replace it with 0.7.9 config.
