### ISSUE TITLE
大神，我安装 0.7.9也卡代码了，求助

### ISSUE THREAD

**Issue by songshanyuwu** [Mr-Zhang-1/Dell5557-I5-6200U-bigsur-Monterey-OC#4]
我遇到了和[ericlesvinicius](https://github.com/ericlesvinicius)一样的错误，在0.7.9版本中
![25813B54-D8C0-45AA-AACA-3FBDB9B9F381_1_105_c](https://user-images.githubusercontent.com/24557504/163677832-486d6b31-05d8-4f86-97b7-918c682d4601.jpeg)

我参照网址http://imacos.top/2021/01/19/0154/中的六3进行了检查，除了第三条没有明白 ，其他的都检查过了。
请大神指点或者帮助，我使用的也是DELL 5557 i5-6200u，
我的邮箱是songzhijunpro@163.com

**Comment by nidemimihihi** [comment]
用0.7.7装，然后自己升级引导
